import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
import { UserProvider } from "@auth0/nextjs-auth0/client"

export const metadata = {
  title: "MPE",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <UserProvider>
            <body className={`antialiased`}>
              {children}
            </body>
          </UserProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
